---

build:
  stage: build
  image:
    name: registry.synyx.cloud/gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"registry.synyx.cloud\":{\"auth\":\"$(printf "%s:%s" "${CONTAINER_REGISTRY_USERNAME}" "${CONTAINER_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --cache=true --reproducible
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "registry.synyx.cloud/infra/nagdash:${CONTAINER_BUILD_TAG}"
      --label "org.opencontainers.image.created=$CI_COMMIT_TIMESTAMP"
      --label "org.opencontainers.image.version=$CONTAINER_BUILD_TAG"
      --label "org.opencontainers.image.revision=$CI_COMMIT_SHA"
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        CONTAINER_BUILD_TAG: latest
    - if: $CI_MERGE_REQUEST_IID
      variables:
        CONTAINER_BUILD_TAG: ${CI_COMMIT_REF_SLUG}
    - if: $CI_COMMIT_TAG
      variables:
        CONTAINER_BUILD_TAG: ${CI_COMMIT_REF_NAME}

deploy:
  stage: deploy
  environment:
    name: production
    url: https://nagdash.synyx.coffee
  before_script:
    - export KUBECONFIG=/tmp/config
    - kubectl config set-cluster synyx --server=https://k8s-master.synyx.coffee:6443 --certificate-authority=$CI_PROJECT_DIR/deploy/ca.crt
    - kubectl config set-credentials deployer --token="$K8S_DEPLOYER_TOKEN"
    - kubectl config set-context default --user=deployer --cluster=synyx --namespace=rabenyx
    - kubectl config use-context default
  script:
    - kubectl version
    - kubectl set image deployment/nagdash nagdash=registry.synyx.cloud/infra/nagdash:$CI_COMMIT_TAG
    - kubectl rollout status -w deployment/nagdash
  image: registry.synyx.cloud/docker.io/bitnami/kubectl:1.22
  rules:
    - if: $CI_COMMIT_TAG
    - when: never
