---
version: 2

# Before building anything, we need to ensure that go modules and generators are set up correctly
before:
  hooks:
    - go mod tidy
    - go generate ./...

# These are the final binaries, that we want to create
builds:
  # This first linux build also contains the defaults used for all other platforms
  - <<: &build_defaults
      binary: tuwat
      # The single main entrypoint binary for tuwat
      main: ./cmd/tuwat
      env:
        # We have no C dependencies
        - CGO_ENABLED=0
      # We want our builds to be reproducible, so we use the commit time as timestamps
      mod_timestamp: '{{ .CommitTimestamp }}'
      ldflags:
        - -s -w
        - -X {{.ModulePath}}/pkg/version.application={{.Binary}}
        - -X {{.ModulePath}}/pkg/version.version={{.Version}}
        - -X {{.ModulePath}}/pkg/version.revision={{.FullCommit}}
        - -X {{.ModulePath}}/pkg/version.branch={{.Branch}}
        - -X {{.ModulePath}}/pkg/version.releaseDate={{.Date}}
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - <<: *build_defaults
    id: darwin
    goos:
      - darwin
    goarch:
      - arm64

# Configure how snapshots are versioned
snapshot:
  version_template: '{{ incpatch .Version }}-dev-{{ .ShortCommit }}'

# Configure what goes into the archives
archives:
  - <<:
      name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
      # Additionally packaged files
      files:
        - LICENSE
        - README*
        - CHANGELOG*
        - config.example.toml
    id: nix
    ids: [ linux, darwin ]
    formats: ['tar.gz']

dockers_v2:
  - images:
      - "synyx/tuwat"
    tags:
      - "{{ .Version }}"
      - "{{ if .IsNightly }}nightly{{ end }}"
      - "{{ if not .IsNightly }}latest{{ end }}"
    labels:
      "org.opencontainers.image.created": "{{ .Date }}"
      "org.opencontainers.image.name": "{{ .ProjectName }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.source": "{{ .GitURL }}"

nfpms:
  - file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}'
    homepage: https://github.com/synyx/tuwat
    description: |-
      Simple, 0-dependencies, dashboard for Nagios/Alertmanager/GitLab...
    maintainer: Jonathan Buch <jbuch@synyx.de>
    license: BSD
    vendor: synyx
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/tuwat/copyright
        file_info:
          mode: 0644

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
