[main]
# golang `text/template` describing where the alert is happening
where = "{{with index .Labels \"Cluster\"}}{{.}}/{{end}}{{first .Labels \"Project\" \"Namespace\" \"Hostname\"}}"
interval = "1m"
#style = "light"


[[rule]]
description = "Ignore Drafts"
[rule.label]
Draft = "true"

[[rule]]
description = "blocked because not needed"
what = "fooo service"

# This adds example alerts in every flavor, useful for development
# Should be disabled in production use
[[example]]
Tag = 'demo'

# The GitHub connector runs out of the box as configured below,
# but keep in mind that GitHub rate limits these requests.
#[[github]]
#Repos = ['synyx/tuwat', 'synyx/buchungsstreber']
#Tag = 'gh'

#[[icinga2]]
#Tag = "synyx"
#URL = "https://icinga2.example.com:5665"
#DashboardURL = "https://icinga2.example.com"
#Insecure = false
#Username = "icingaweb2"
#Password = "aBaBaBaBaBaBaBaBaBaB"
#
#[[nagiosapi]]
#Tag = "dev"
#URL = "https://nagiosapi.example.com:8080"
#NagiosURL = "https://icinga.example.com"
#
#[[alertmanager]]
#Tag = "test"
#Cluster = "test"
#URL = "https://alertmanager.example.com"
#[alertmanager.OAuth2Creds]
#ClientID = "client"
#ClientSecret = "example-eaeb-4451-926e-2643c07b91b1"
#TokenURL = "https://login.example.com/auth/realms/realm/protocol/openid-connect/token"
#
#[[gitlabmr]]
#Tag = "sysops"
#URL = "https://gitlab.example.com"
#BearerToken = "aBaBaBaBaBaBaBaBaBaB"
##Projects = ["group/project"]
##Groups = ["group"]
#
#[[patchman]]
#Tag = "dev"
#URL = "https://patchman.example.com"
#Insecure = true
#Username = "user"
#Password = "password"
#Filter = { tag = "test", domain = "1", os = "7", osgroup = "2", arch = "5", reboot_required = "True" }
#
#[[redmine]]
#Tag = "tkt"
#URL = "https://redmine.example.com"
#BearerToken = "example3f5bb1632f40bde25d315d53bdec83e"
#
#[[graylog]]
#Tag = 'graylog'
#URL = "https://graylog.example.com"
#TimeRange = 600 # query timerange in seconds
#Username = "example3f5bb1632f40bde25d315d53bdec83e"
#Password = "token"
#
#[[wizio]]
#Tag = 'wizio'
#URL = "https://your-api.app.wiz.io"
#StatusFilter = ["OPEN", "IN_PROGRESS"]
#SeverityFilter = ["CRITICAL", "HIGH"]
#NumberOfIssues = 20
#[wizio.OAuth2Creds]
#ClientID = "example-12143412"
#ClientSecret = "secretsecret"
#TokenURL = "https://auth.app.wiz.io/oauth/token"
#Endpoapi.eu13intParams = {"audience" =  ["wiz-api"]}