---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: infra
  name: nagdash
  labels:
    app: nagdash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nagdash
  template:
    metadata:
      labels:
        app: nagdash
    spec:
      imagePullSecrets:
        - name: registry.synyx.cloud
      containers:
        - name: nagdash
          imagePullPolicy: Always
          image: registry.synyx.cloud/infra/nagdash:v0.1.1
          ports:
          - containerPort: 80
          volumeMounts:
          - name: nagdash-config-volume
            mountPath: /var/www/html/config.php
            subPath: config.php
      volumes:
        - name: nagdash-config-volume
          configMap:
            name: nagdash


---

kind: Service
apiVersion: v1
metadata:
  namespace: infra
  name: nagdash
spec:
  selector:
    app: nagdash
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: infra
  name: nagdash
spec:
  rules:
  - host: k8s-nagdash.synyx.coffee
    http:
      paths:
      - path: /
        backend:
          serviceName: nagdash
          servicePort: 80
  - host: nagdash.synyx.coffee
    http:
      paths:
      - path: /
        backend:
          serviceName: nagdash
          servicePort: 80
