name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: read

jobs:
  build-before-release:
    uses: ./.github/workflows/ci.yml

  release:
    runs-on: ubuntu-latest
    needs: build-before-release
    permissions:
      contents: write # needed to write releases
      packages: write # needed for ghcr access
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch tags
        run: git fetch --force --tags

      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: true

      # Those are needed so goreleaser can build multi-arch docker images
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Finally run the release
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
